### ISSUE TITLE
Truffle will not unbox ZeppelinOS 

### ISSUE THREAD

**Issue by DSamuelHodge** [zeppelinos/zepkit#10]
PS C:\Users\dshod\Git\truffle\my-app> truffle unbox zeppelinos/zepkit

√ Preparing to download
√ Downloading
√ Cleaning up temporary files
× Setting up box
Error: Error: Error: Command failed: npm install && cd client && npm install
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dshod\AppData\Roaming\npm-cache\_logs\2019-04-29T05_01_05_480Z-debug.log

    at Object.unbox (C:\Users\dshod\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-box\box.js:69:1)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
Truffle v5.0.14 (core: 5.0.14)
Node v12.0.0
PS C:\Users\dshod\Git\truffle\my-app>

**Comment by rrecuero** [comment]
Instead of truffle unbox, Can you try cloning this repo and running this:
`
npm install && cd client && npm install
`

**Comment by DSamuelHodge** [comment]
Cloned repo and ran the script. That did not work. The issue seems to be with Windows 10. I switched to Ubuntu and was able to install Truffle, Ganache CLI, and ZeppelinOS.
