### ISSUE TITLE
GSN with ERC20 Compliant Smart Contract

### ISSUE THREAD

**Issue by SirPhemmiey** [zeppelinos/zepkit#108]
I'm following the tutorial here: https://docs.openzeppelin.com/sdk/2.5/gsn-dapp. And I have successfully done everything required (though locally on Ganache). But i'm facing a problem. I am building an ERC20 compliant smart contract. And i need to call `approve()` before calling `transferFrom()` but if I call the `approve()` function it returns "Error: Could not get relay hub address from recipient at <tokenAddress>". And i guess the reason is because the ERC20 token is not configured to accept relayed calls. But i can't call the `transferFrom()` function because it will revert. Please, how do i go about this problem with GSN?

**Comment by abcoathup** [comment]
Hi @SirPhemmiey,

I suggest that you post this question in the support category of the community forum so that the entire community could assist: https://forum.openzeppelin.com/c/support/17

It would be helpful if you could advise if you are developing both the ERC20 token and the contract receiving the ERC20 token or whether you are only developing the receiving contract.

**Comment by SirPhemmiey** [comment]
Okay, i would do that. 

Thanks for the swift response @abcoathup. 

For now (development phase), i am developing both the ERC20 token and contract transferring the token. But in production, i would use ERC20 tokens already deployed.

**Comment by SirPhemmiey** [comment]
Hi @abcoathup, nobody has responded about 11 hours ago :(

**Comment by abcoathup** [comment]
Sorry about that. I am in Melbourne Australia. It’s on my todo list for this morning.

**Comment by abcoathup** [comment]
Hi @SirPhemmiey, I have responded in the forum: https://forum.openzeppelin.com/t/gsn-with-erc20-compliant-smart-contract/1921/2

I suggest we close this issue and continue the discussion in the forum.

**Comment by SirPhemmiey** [comment]
Sure!
