### ISSUE TITLE
Out of gas when initializing Counter in zepkit for truffle (5.0.17) and ganache-cli (6.4.3)

### ISSUE THREAD

**Issue by abcoathup** [zeppelinos/zepkit#18]
Following instructions for hot reloading demo https://blog.zeppelinos.org/solidity-hot-reloading-using-zepkit/ but using later versions of truffle (5.0.17) and ganache-cli (6.4.3).

When I initialized the Counter `npx zos create Counter --init initialize --args 2`
I got an out of gas error `Returned error: VM Exception while processing transaction: out of gas`

I solved by specifying the gas as 6721975 (ganache-cli gas limit) in truffle-config.js, so box may need to be updated to include (unless there is a better way to resolve).

```
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  networks: {
    development: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*",
      gas: 6721975,
    },
...
```

**Comment by ylv-io** [comment]
Hey @abcoathup! Ganache after version ganache-cli@6.3.0 has issues with gas estimation. That is why article pinned down it to ganache-cli@6.3.0.
Yes, another approach would be to specify some gas in network config but it might be not enough for some other contracts. I don't see the benefit of upgrading ganache at that time.
