### ISSUE TITLE
Compiled with warnings

### ISSUE THREAD

**Issue by takattty** [zeppelinos/zepkit#19]
Hi.
I was running 
```
npm run start
```

The result
```
Compiled with warnings.

../contracts/Counter.sol
Error: Command failed: zos push --network development --no-interactive
error: unknown option `--no-interactive'

../contracts/Wallet.sol
Error: Command failed: zos push --network development --no-interactive
error: unknown option `--no-interactive'

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

```
What's the keywords? 
What should i search?

**Comment by takattty** [comment]
But I can see it.
It is zepkit running page.
→http://localhost:3000/counter

![スクリーンショット 2019-05-15 19 21 23](https://user-images.githubusercontent.com/43886741/57768540-ccdd9300-7746-11e9-8073-844e92008cf4.png)

**Comment by takattty** [comment]
Add this photo.
running ``zos  push``

The result
```
Using session with network development, sender address 0x~~
Compiling contracts with Truffle...
Cannot read property 'match' of undefined
Created zos.dev-1557913295593.json
```



![スクリーンショット 2019-05-15 19 25 35](https://user-images.githubusercontent.com/43886741/57769064-f3e89480-7747-11e9-99a1-34288409bfba.png)

**Comment by ylv-io** [comment]
Hey @takattty. Thanks for trying ZepKit!
We are about to release a new version of ZeppelinOS and got a bit ahead of ourselves.
Can you reinstall ZepKit with exactly these versions `npm install -g truffle@5.0.2 ganache-cli@6.3.0 zos@2.2.0`?
If you'll have any trouble feel free to create another issue.

**Comment by takattty** [comment]
Hi, @ylv-io . 
Thanks to you, I finished all this tutorial(https://blog.zeppelinos.org/getting-started-with-zepkit/)
Thank you for giving me good advice.

Actually, There is an event to use Zepkit at May 22th in Japan.(https://hashhub.connpass.com/event/130255/)

so, may i create an article that is added some code and instructions in this tutorial for use in the event??

Thank you so much.

**Comment by ylv-io** [comment]
Hey @takattty.
Absolutely. Go ahead! 
ありがとう
