### ISSUE TITLE
"Truffle Box Does Not Exist"

### ISSUE THREAD

**Issue by Kyrrui** [zeppelinos/zepkit#2]
When following along Zepkit's installation instructions, the command 'truffle unbox zeppelinos/zepkit' returns this error.
<img width="1007" alt="screen shot 2019-02-25 at 9 44 23 pm" src="https://user-images.githubusercontent.com/8539426/53383781-c0ffe300-3946-11e9-906e-f4ca40c8705e.png">

**Comment by rrecuero** [comment]
hey Kyle, which truffle version are you using? can you try with truffle 5? @Kyrrui

**Comment by Kyrrui** [comment]
Upgrading to the latest version of Truffle worked, thanks!
