### ISSUE TITLE
`npm run start` is hanging

### ISSUE THREAD

**Issue by itinance** [zeppelinos/zepkit#25]
Hi there

starting from scratch following all instructions in the README, when I run `npm run start` in the `client?`-directory, the process is hanging with "Starting the development server...". The browser gets opened referring to "localhost:3000", but nothing happens. It will timeout later.

No further details are provided in the console. It just hangs. 
I'm pretty sure that no other application is listening on this port (```sudo lsof -n -i -P | grep 3000```).

Tested on Macbook Pro running MacOS Mojave. 

```
$ node -v
v10.11.0

$ npm -v
6.9.0

$ zos --version
2.3.0
```

Is anybody else facing this issue?

I remember it has worked exactly one week ago without any issues. Maybe some dependencies have changed and broke it somewhere?

**Comment by ylv-io** [comment]
Hey @itinance. I am pretty sure it is `zos@2.3.0`. Can you try version `zos@2.2`? We'll add full support of version `zos@2.3` with new cool features next week but for now please sick to v2.2.

**Comment by itinance** [comment]
With zos@2.2.0 it works! Thanks a lot :)

**Comment by ylv-io** [comment]
No problem. Sorry for inconvenience and soon will drop more cool features!
