### ISSUE TITLE
Out of Gas: Counter deployment failed with error: Returned error: sender doesn't have enough funds to send tx.

### ISSUE THREAD

**Issue by MrsBookik** [zeppelinos/zepkit#26]
I did everything that was listet in README and official tutorial.

Ganache-CLI V6.3.0 is running in another terminal session providing 10 Accounts full of 100 ETH each.

How ever, when I want to "zos push" the default Contract "Counter.sol", the following error appears:

> Counter deployment failed with error: Returned error: sender doesn't have enough funds to send tx. The upfront cost is: 351843720888280000000000 and the sender's account only has: 100000000000000000000

The full output:

```
$ zos push
Compiling contracts with Truffle...

Compiling your contracts...
===========================
> Compiling ./contracts/Counter.sol
> Compiling ./contracts/Wallet.sol
> Compiling openzeppelin-eth/contracts/access/Roles.sol
> Compiling openzeppelin-eth/contracts/access/roles/MinterRole.sol
> Compiling openzeppelin-eth/contracts/access/roles/PauserRole.sol
> Compiling openzeppelin-eth/contracts/lifecycle/Pausable.sol
> Compiling openzeppelin-eth/contracts/math/SafeMath.sol
> Compiling openzeppelin-eth/contracts/ownership/Ownable.sol
> Compiling openzeppelin-eth/contracts/token/ERC20/ERC20.sol
> Compiling openzeppelin-eth/contracts/token/ERC20/ERC20Detailed.sol
> Compiling openzeppelin-eth/contracts/token/ERC20/ERC20Mintable.sol
> Compiling openzeppelin-eth/contracts/token/ERC20/ERC20Pausable.sol
> Compiling openzeppelin-eth/contracts/token/ERC20/IERC20.sol
> Compiling openzeppelin-eth/contracts/token/ERC20/StandaloneERC20.sol
> Compiling zos-lib/contracts/Initializable.sol
> Artifacts written to /xxxxxxxxxx/build/contracts
> Compiled successfully using:
   - solc: 0.5.0+commit.1d4f565a.Emscripten.clang


Using session with network local, sender address 0x6c32ee3d8dcd2a88142c6ba35fc97ce92904f086, timeout 3600 seconds
WARNING: Address 0x6c32ee3d8dcd2a88142c6ba35fc97ce92904f086 is not checksummed. Consider checksumming it to avoid future warnings or errors.
Validating contract Counter
Uploading Counter contract as Counter
Deploying logic contract for Counter
Counter deployment failed with error: Returned error: sender doesn't have enough funds to send tx. The upfront cost is: 351843720888280000000000 and the sender's account only has: 100000000000000000000
Created zos.dev-1559219644112.json
```

zos-version: 2.3.0
ganache-cli: 6.3.0
ganache-core: 2.4.0

**Comment by MrsBookik** [comment]
Why is the Gas consumption so high?

**Comment by ylv-io** [comment]
Hey @MrsBookik.
> npm install -g truffle@5.0.2 ganache-cli@6.3.0 zos@2.2.0
Readme says to use version `zos@2.2.0`. Can you give it a run with this version?

**Comment by MrsBookik** [comment]
The error persists:

Ganache CLI v6.3.0 (ganache-core: 2.4.0)
zos: 2.2.0
Truffle v5.0.2

**Comment by itinance** [comment]
I ran into the same issue, with both versions of zos@2.2.0 and 2.3.0.
I compared then truffle-config.js with that file from an empty "zos init"-boilerplate and found the following difference. 

After adding these lines `gas` and `gasPrice`  into the zepkit-boilerplate, "zos push" will work as expected:

```
module.exports = {
  networks: {
    local: {
      host: 'localhost',
      port: 8545,
      gas: 5000000,
      gasPrice: 5e9,
      network_id: '*',
    }
  }
}

```

Please consider also the port number. "zos init" will give you 8454, while the zepkit boilerplate is shipped with 9454.

**Comment by spalladino** [comment]
I was about to suggest https://github.com/zeppelinos/zos/pull/896 as a possible culprit, but it was added on 2.3, so it should not happen when rolling back to 2.2. Also, the consumption should be at most 0.13 ETH (`blockGasLimit * gasPrice = 6721975 * 20000000000`), which is way below the 100 ETH owned by each account by default.

**Comment by spalladino** [comment]
I've just gone back to the [original issue in the forum](https://forum.zeppelin.solutions/t/how-to-interact-with-smartcontracts-with-the-reactjs-web-application/678/3), where it is mentioned that ganache is run with _unlimited gas_ (ie `---gasLimit 0xfffffffffff`). This will definitely cause this error. 

I've filed this issue in `zos` to track it, which includes two workarounds. @ylv-io I think we can close this issue, since it's actually a problem in the CLI.

**Comment by ylv-io** [comment]
Absolutely. Just in case there a new cool feature in github called `Transfer Issue`. I think a lot of `zos` issue will land in ZepKit. So we might use it in future!
