### ISSUE TITLE
zos unpack zepkit omits the previous startup instructions.

### ISSUE THREAD

**Issue by crazyrabbitLTC** [zeppelinos/zepkit#27]
When previously using truffle to unbox zepkit, at the end of the process we were greeted with: 

```

✔ Preparing to download
✔ Downloading
✔ Cleaning up temporary files
✔ Setting up box

Unbox successful. Sweet!

Commands:

  Add a contract:                            zos add <contract_name>
  Create a session:                          zos session --network <network_name> --from <default_address> --expires 36000
  Compile all contract and deploy them:      zos push --deploy-dependencies
  Create upgradeable instance of a contract: zos create <contract_name>
  Update an upgradeable contract:            zos update <contract_name>
  Test contracts:                            truffle test
  Test dapp:                                 cd client && npm test
  Run dev server:                            cd client && npm run start
  Build for production:                      cd client && npm run build
  Start from a blank slate:                  npm run start-blank
```

However when using `zos unpack zepkit` we are welcomed at the end of the unpack with: 

```
The kit is ready to use. Amazing!

Quick Start
Run your local blockchain:
> ganache-cli --secure -u 0 -u 1 -u 2 --deterministic
Initialize the ZeppelinOS project:
> zos init zepkit
Go to the client directory:
> cd client
Run the React app:
> npm run start
Continue in your browser!
More at https://github.com/zeppelinos/zepkit/tree/stable
```

The previous version I believe was more informative for developers. In my opinion!

**Comment by ylv-io** [comment]
The reason for a changed as it is printed in a terminal. Once you run a few commands it is hard to get back to the quick command reference. Once you clear your terminal then there is no way to go back. That is quick reference was replaced by quick start. Full command reference is available at the github readme which once opened stays there.
Was it better to lookup commands in a terminal for you @crazyrabbitLTC ?

**Comment by crazyrabbitLTC** [comment]
Visually I think the old style stands out more as being clearer and easier to read IMHO. If we want to do it this way, maybe we can dress it up a bit? Make it prettier? Honestly though, I do like seeing the other commands that are available. Maybe we could have both?

**Comment by ylv-io** [comment]
Kits were designed to have the post install message fully customizable.
Check out [kit.json](https://github.com/zeppelinos/zepkit/blob/stable/kit.json).
I 100% trust you on that matter because you know better how people react to just installed kits. You can fork a kit and play with the message using `zos unpack crazyrabbitLTC/zepkit` or just copy string  and echo it in a terminal. If you'll be happy with a change I am happy to merge it.
If I can do anything else, please let me know.

**Comment by crazyrabbitLTC** [comment]
I didn't know we could customize it! That's pretty cool. I think in general this isn't of a high enough priority to worry about, it's really only cosmetic. I'll take a look at forking the kits though, I like that idea- crazyrabbit kits!
