### ISSUE TITLE
Issue in setting up zepkit

### ISSUE THREAD

**Issue by c-jain** [zeppelinos/zepkit#30]
![error](https://user-images.githubusercontent.com/26558364/59428813-f815d980-8dfb-11e9-9cd7-e08c7e5512d2.png)
As it is visible in the screenshot, I did not get a **green check** in the "setting up box". Anyone know why it is happening and will it cause any issue in the future?

**Comment by ylv-io** [comment]
Hey @c-jain. Sorry to hear that it happened to you. I've never seen error like that. Can you try to run `zos unpack tutorial` instead? It should give you updated version of a ZepKit.

**Comment by c-jain** [comment]
![Screenshot from 2019-06-18 01-28-36](https://user-images.githubusercontent.com/26558364/59632761-97bec900-9168-11e9-977a-1531832f2fc6.png)
Hey @ylv-io. Thanks for replying. But it looks like `unpack` is not a command.

**Comment by ylv-io** [comment]
Which version of zos you are running? `zos --version`? As of latest zos 2.3.1 `unpack` is supported.

**Comment by c-jain** [comment]
Thanks, I updated the zos to 2.3.1 and now it supports `unpack`.

**Comment by ylv-io** [comment]
Nice. If you have any other issue feel free to post them!
