### ISSUE TITLE
Out of gas: Test networks require a different HD-Wallet-Path against to Mainnet

### ISSUE THREAD

**Issue by itinance** [zeppelinos/zepkit#32]
**Long story short:** 

I sent some Test-Ether on Ropsten into the first address, that was derived with MyCrypto out of my Mnmonics, but the deployment using truffle or `zos`-Tool was constantly running out of gas, no matter which funds was sent. And here is why this happened and how to solve:

**Long Story:**

When we import a Mnemonic into MyCrypto or MyEtherWallet (or other Tools) for Ropsten-Network, it derives the address with the following path: `m/44'/1'/0'/0`, while `truffle-hdwallet-provider` constantly is using `m/44'/60'/0'/0/` no matter wich network will be used.

`m/44'/60'/0'/0/` is the derivation path for Ethereum Mainnet, while all other Testnets across all coins share `m/44'/1'/0'/0` for path derivation.

Therefor, I get a different address on MyCrypto as the first address than it will be used by `truffle-hdwallet-provider`.

This means, when I transfer Test-Ether on Ropsten Network to the first address out of my Mnemonic, it will be a different address as the HDWalletProvider will generate with our default settings.

**Example:**

Mnemonic: "tooth spike smile swarm adapt history motion salt outdoor document observe cloth"

MyCrypto Ropsten (using `m/44'/1'/0'/0`): `0x9dbFAFB5Edd1D69aCaC1C104C526C4ACDc20F3Ae`

truffle-HDWallet-provider with default settings (using `m/44'/60'/0'/0`): `0xC0306fe5c3E90025AD56832A4399670be51b3Eec`

Thus, a deployment of contracts, that are based on `truffle-config.js` as it is used in this repository, will raise "Out of gas"-exception because different addresses will be used. I would send Test-Ether to the address, that was generated by MyCrypto. And truffle-hdwallet-provider expects the second address, which probably has no funds nor could sign any transaction due to missing private key.

Fortunately the constructor of `truffle-hdwallet-provider` offers an argument for the `wallet_hdpath` that should be used for address derivation. So for using Ropster addresses (and even all other Testnetworks) properly with MyCrypto / MyEtherWallet, the following constructor is required to make transactions work as expected.

```
ropsten: {
  provider: () => new HDWalletProvider(
    process.env.DEV_MNEMONIC, "https://ropsten.infura.io/v3/" + infuraProjectId, 
        0, 1, true, "m/44'/1'/0'/0/"
    ),
  networkId: 3,       // Ropsten's id
},

```

Explanation of the parameters:

```
0 = start with first address
1 = derive only 1 addresses
true = sharedNonce (default)

“m/44’/1’/0’/0/” = BIP44 derivation path that is used for test networks (across all coins)
```

We should reflect this in `truffle-config.js` as well.

**Comment by ylv-io** [comment]
Hey @itinance. Thanks again for the contribution. One thing I've spotted that [metamask is also using ](https://github.com/MetaMask/eth-hd-keyring/blob/master/index.js#L8) a `m/44'/60'/0'/0/` derivation path. And a lot of users do use metamask for testnet. I think we should give users options here. What do you think?

**Comment by itinance** [comment]
Whew... that's really a pitty from Metamask. Seems to be more helpful if we leave the code as is and just add a note about it describing the right derivation path for MyCrypto users as a comment.

Or add more records network-config for "ropsten_mycrypto", "kovan_mycrypto"? What would you prefer? I will add these changes then into this PR

**Comment by ylv-io** [comment]
I think we should provide utility function with defaults and other option as a comment:

```javascript

const configTestNetwok = (network, path = "m/44'/60'/0'/0/", gas = 4465030, gasPrice = 10000000000) => ({
  provider: () => new HDWalletProvider(
    process.env.DEV_MNEMONIC, `https://${network}.infura.io/v3/` + infuraProjectId, 
        0, 1, true, path
    ),
  networkId: 3,
  gas: gas,
  gasPrice: gasPrice,
});

ropsten: configTestNetwok('ropsten'),
// support MyEtherWallet
// ropsten: configTestNetwok('ropsten', "m/44'/1'/0'/0/"),

```

Something like this.

**Comment by itinance** [comment]
Sounds good. We still need to take into account the `networkId` as well as parameter because it has an own value for each network (as you certainly know). I will give it a try tomorrow (CET)

**Comment by ylv-io** [comment]
I've refactored truffle-config so it is easy to config it.
