### ISSUE TITLE
Fix infura API token usage in truffle config

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zepkit#49]
The current truffle config defines an `INFURA_ID` which is never used, and uses `process.env.INFURA_API_KEY` instead. We should use the env variable if set, but fallback to the pre-set infura ID otherwise.

To make matters worse, `.env.example` defines (and `App.js` uses) an env variable `REACT_APP_INFURA_KEY`. We should change the env var being used in truffle config so it matches this one, otherwise the user needs to define two env vars with the same value.

**Comment by ylv-io** [comment]
I've fixed usage of `INFURA` token and added default fallback. Yet I haven't figure out clean and easy way to share Infura token between both projects.
