### ISSUE TITLE
Merge master & stable branches

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zepkit#50]
Master and stable branches have diverged (20 ahead, 38 behind). We need to merge them or clearly identify where to keep developing.

Update: @ylv-io pointed out that `master` is being used for truffle box, while `stable` for zepkit. Let's just add a note on the README explaining this for future reference.

**Comment by ylv-io** [comment]
Master branch is a truffle tutorial box there stable branch is a `unpack starter`.
