### ISSUE TITLE
Integrate GSN into starter-kit

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zepkit#51]
We currently have two boxes in starter kit that demo how it is used: one with a local provider, another with an injected one.

While we could add one with a GSN provider, it is not possible to show how to use it because none of the boxes actually _send_ a tx, which is the main feature of GSN.

We need to decide:
- Are we going to include a demo box for the GSN in the kit?
- If so, should it run locally or on a testnet?
- If locally, how are we managing the GSN development setup?
- If remotely, for which contract?

I'd suggest going with a local demo, so we force ourselves to also handle the GSN development setup for the user, which may not yet be trivial.

The other point to discuss is whether we want to include this into the vanilla kit, into a GSN dedicated one, or into the tutorial one.

**Comment by ylv-io** [comment]
[Done](https://github.com/OpenZeppelin/starter-kit-gsn)! 🚢
