### ISSUE TITLE
Error: Cannot find module './build/Release/scrypt'

### ISSUE THREAD

**Issue by sampsojp** [zeppelinos/zepkit#52]
Compiled with warnings.

./src/components/Header/index.js
  Line 3:  'logo' is defined but never used  no-unused-vars

./src/components/Footer/index.js
  Line 5:  'pencil' is defined but never used  no-unused-vars

../contracts/Counter.sol
Error: Command failed: '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/.bin/oz' compile
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module './build/Release/scrypt'
Require stack:
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/scrypt/index.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/scrypt.js/node.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/web3-eth-accounts/src/index.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/web3-eth/src/index.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/web3/src/index.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/upgrades/lib/artifacts/ZWeb3.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/upgrades/lib/helpers/encodeCall.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/upgrades/lib/index.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/cli/lib/bin/oz-cli.js
    at Module.require (internal/modules/cjs/loader.js:683:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/scrypt/index.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/scrypt.js/node.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/web3-eth-accounts/src/index.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/web3-eth/src/index.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/web3/src/index.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/upgrades/lib/artifacts/ZWeb3.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/upgrades/lib/helpers/encodeCall.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/upgrades/lib/index.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/cli/lib/bin/oz-cli.js'
  ]
}

../contracts/Wallet.sol
Error: Command failed: '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/.bin/oz' compile
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module './build/Release/scrypt'
Require stack:
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/scrypt/index.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/scrypt.js/node.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/web3-eth-accounts/src/index.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/web3-eth/src/index.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/web3/src/index.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/upgrades/lib/artifacts/ZWeb3.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/upgrades/lib/helpers/encodeCall.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/upgrades/lib/index.js
- /mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/cli/lib/bin/oz-cli.js
    at Module.require (internal/modules/cjs/loader.js:683:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/scrypt/index.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/scrypt.js/node.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/web3-eth-accounts/src/index.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/web3-eth/src/index.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/web3/src/index.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/upgrades/lib/artifacts/ZWeb3.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/upgrades/lib/helpers/encodeCall.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/upgrades/lib/index.js',
    '/mnt/c/Users/samps/projects/wsl/openzeppelin/starterkit/tutorial/node_modules/@openzeppelin/cli/lib/bin/oz-cli.js'
  ]
}

**Comment by EnchanterIO** [comment]
Just my 2 cents from top of my head, try with `Node v10.13.0` https://github.com/OpenZeppelin/starter-kit/issues/59

**Comment by ylv-io** [comment]
You are missing `scrypt` dependency which had some issues compiling on some platforms especially windows. We just bumped all the dependencies. Give it another try. Should work.
