### ISSUE TITLE
Migrate from 3 years old `scrypt` compatible with only Node v10

### ISSUE THREAD

**Issue by EnchanterIO** [zeppelinos/zepkit#59]
Hi, I had a lot of issues setting up the starter kit. Took me quiet some time to figure the issue. The problem is that all of the libraries, including the tabookey depend on the [scrypt package](https://www.npmjs.com/package/scrypt) which is 3 years old and doesn't compile Keccak alg and others on `Node v12`.

In order to setup the project, I had to install `node v10.13.0`.

I think it would be great if OpenZeppelin woud support `web3@1.2.0` as well as latest Node version.

Great work on the Gas Station though! I hope I can integrate today the GSN into my project's smart contracts and setup the ReplayServer using your kit :)

**Comment by ylv-io** [comment]
Hey @EnchanterIO! Thanks for dropping in! We almost fully migrated to web3@1.2.0. Kits will migrate finish migration next week.
Regarding scrypt package. Yes, it is pain. As you mentioned there are a lot of other libraries which depend on it. Any idea how to work around it?

**Comment by ylv-io** [comment]
Hey @EnchanterIO! Happy to announce that all starter kits and other OpenZeppelin dependencies have been migrated to web3@1.2.1.

**Comment by EnchanterIO** [comment]
That's amazing! Gg @ylv-io @nventuro @abcoathup.
