### ISSUE TITLE
Unable to fund my Counter contract

### ISSUE THREAD

**Issue by EnchanterIO** [zeppelinos/zepkit#60]
I have setup the RelayHub, ganache, frontend but when I execute `npx oz-gsn fund-recipient --recipient 0x9b1f7F645351AF3631a656421eD2e40f2802E6c0` it seems to succeed but my contract has still 0 funds afterwards.

Here is a picture with all the details:
<img width="859" alt="Screen Shot 2019-08-20 at 12 41 45" src="https://user-images.githubusercontent.com/3595242/63340790-1d691b80-c348-11e9-99ea-8d833f9d437b.png">
<img width="1440" alt="Screen Shot 2019-08-20 at 12 40 41" src="https://user-images.githubusercontent.com/3595242/63340801-20fca280-c348-11e9-8bef-11de976dce63.png">

Any idea what could be wrong?

Also, in order to enable GSN for Counter, I had to modify the contract but the starter kit is coming with no `Migrations.sol` from Truffle, neither the deployment script so I had to add the following 2 files:

`client/contracts/Migrations.sol`
```solidity
pragma solidity ^0.5.0;

contract Migrations {
  address public owner;
  uint public last_completed_migration;

  constructor() public {
    owner = msg.sender;
  }

  modifier restricted() {
    if (msg.sender == owner) _;
  }

  function setCompleted(uint completed) public restricted {
    last_completed_migration = completed;
  }

  function upgrade(address new_address) public restricted {
    Migrations upgraded = Migrations(new_address);
    upgraded.setCompleted(last_completed_migration);
  }
}
```

and:
`client/migrations/2_deploy_counter.js`
```
const Counter = artifacts.require("Counter.sol");

module.exports = (deployer) => {
  deployer.deploy(Counter).then(() => {
    console.log("Counter.sol successfully deployed!");
  });
};
```

## Questions:

1. Why my funded recipient has still 0 ETH?
2. Why are the migrations files and scripts missing? Did I skip some step or it's a bug?
3. I think the UI should display the counter button right away but explain in the UI why it's disabled. I only realized I can interact with Counter contract using the UI by checking the code. Should be more obvious, as the first thing I want to do as a user when using the oz-gsn-kit is to test making transactions and see I don't pay gas for them.

```javascript
          {(!!funds || !!balance) && (
            <React.Fragment>
              <div className={styles.label}>
                <strong>Counter Actions</strong>
              </div>
              <div className={styles.buttons}>
                <Button onClick={() => increase(1)} size="small">
                  {sending ? <Loader className={styles.loader} color="white" /> : <span> Increase Counter by 1</span>}
                </Button>
                <Button onClick={() => decrease(1)} disabled={!(methods && methods.decreaseCounter)} size="small">
                  {sending ? <Loader className={styles.loader} color="white" /> : <span> Decrease Counter by 1</span>}
                </Button>
              </div>
            </React.Fragment>
          )}
```

## Update:
Atm, I am still debugging why my contract has 0 ETH. I will post update if I find out.

## Update 20.8.2019 13:13 CET
```
  console.log(currentBalance.toString());

  if (currentBalance.lt(targetAmount)) {
    const value = targetAmount.sub(currentBalance);
    console.log(value);
    await relayHub.methods.depositFor(recipient).send({ value, from });
    return targetAmount;
  } else {
    return currentBalance;
  }
```

Output:
```
1000000000000000000

Recipient 0x9b1f7F645351AF3631a656421eD2e40f2802E6c0 balance is now 1000000000000000000 wei
```

Outputs 1 ETH, which means the recipient is apparently already funded... but querying Ganache balance still outputs 0 hm 

## Update 20.8.2019 15:11

Soooolved. So many moving pieces heh. The problem was that the Counter.sol was a valid RelayRecipient but wasn't initialized. I was missing this function call:

```javascript
const Counter = artifacts.require("Counter.sol");

module.exports = (deployer) => {
  deployer.deploy(Counter).then((instance) => {
    console.log("Counter.sol successfully deployed!");
    console.log("Initializing the GSN...");
    instance.initialize(0).then(() => {
      console.log("Counter.sol successfully initialized with GSN!");
    });
  });
};
```

Which performs:

```solidity
function initialize(uint num) public initializer {
     GSNRecipient.initialize();
     _owner = _msgSender();
    count = num;
  }
```

... I thought the initialize() is part of a contract constructor and was already executed.

Now the UI looks better and all parts seems to work well. Next doubt, who is the `msg.sender` behind "increaseCounter()" call? Gonna verify.

Feel free to use my questions for your "user research" so you know how devs are thinking about the GNS implementation :)

## Update 20.8.2019 15:47

Simply modified the `increaseCounter()` function and some React code and...

```solidity
function increaseCounter(uint256 amount) public {
    count = count + amount;
    counterIncrementer = _msgSender();
  }
```

Wopaa! Works like charm now @ylv-io and @spalladino!

<img width="1440" alt="Screen Shot 2019-08-20 at 15 44 12" src="https://user-images.githubusercontent.com/3595242/63352941-426a8800-c362-11e9-95f0-970512d16276.png">
<img width="933" alt="Screen Shot 2019-08-20 at 15 43 54" src="https://user-images.githubusercontent.com/3595242/63352943-43031e80-c362-11e9-9514-c3f167d4e0f2.png">

Here is the code if somebody wants to check it out: https://github.com/EnchanterIO/starter-kit-gsn/commits/master

Gg.

**Comment by abcoathup** [comment]
Glad you got it working.  

The starter kit used OpenZeppelin SDK so you can deploy the contract using `openzeppelin create`.

I have replied in the forum too:
https://forum.openzeppelin.com/t/gsn-starter-kit-hands-on-experience/1212/2

**Comment by nventuro** [comment]
As mentioned, the issue was the Counter contract was not initialized (i.e. `initialize` was not called). Most tools use `IRelayRecipient`'s `getHubAddr` method to get the recipient's RelayHub instance address (there's a single global one currently, but this may change if upgraded versions of RelayHub are released), and this value was uninitialized.

Closing the issue here, we'll continue gathering feedback on the forum post.

**Comment by ylv-io** [comment]
Hey @EnchanterIO! Thanks for trying it and I am impressed how you were able to figure it out yourself!

**Comment by vibern0** [comment]
Thank you so much. I was having the same problem.
Maybe this step is missing here https://docs.openzeppelin.com/sdk/2.5/gsn-dapp ?

**Comment by abcoathup** [comment]
Hi @obernardovieira 
https://docs.openzeppelin.com/sdk/2.5/gsn-dapp includes a note about calling initialize.  
>It is important that you remember to call the initialize() function when creating the contract, as this will be sure to get your contract ready to be used in the GSN.

Do you think the wording can be improved?
